### ISSUE TITLE
PCA image data not loading

### ISSUE THREAD

**Issue by JM-Hansen** [learn-co-curriculum/dsc-pca-and-digital-image-processing#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/assignments/189649?module_item_id=422185

## Issue Subtype

- [X ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue

In line 2 od the code where the data is downloaded an error pops up:
URLError: <urlopen error [Errno 99] Cannot assign requested address>

### Source

```
data = fetch_olivetti_faces()
```

### Concern

Code throws an error, the URL and dataset source through sklearn needs to be checked on this.
Can't load data for the rest of the notebook to function properly.

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [X ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue @JM-Hansen :wave:. We are looking into this issue on SaturnCloud at this time. I was able to reproduce the error and will follow up with you once it is resolved on SaturnCloud.

If you would like to continue working on this lesson, it will run on your local machine using the following steps:
1. Open a terminal window
2. Change into the directory you wish to clone the repository into using `cd`
3. Clone the repository using `git@github.com:learn-co-curriculum/dsc-pca-and-digital-image-processing.git`
4. Activate the `learn-env` environment with `conda activate learn-env`
5. Change into the repository directory using `cd dsc-pca-and-digital-image-processing`
6. Start your local jupyter server with `jupyter notebook`

Let me know what questions you have.
